[package]
name = "dawn-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
dawn-protocol = { path = "../crates/dawn-protocol" }

[[bin]]
name = "decode_client_message"
path = "fuzz_targets/decode_client_message.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_server_message"
path = "fuzz_targets/decode_server_message.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
