[package]
name    = "dawn-simulation"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simulate"
path = "src/main.rs"

[dependencies]
dawn-core        = { path = "../dawn-core" }
dawn-ecs         = { path = "../dawn-ecs" }
dawn-event-store = { path = "../dawn-event-store" }
dawn-actor       = { path = "../dawn-actor" }
rand             = { workspace = true, features = ["small_rng"] }
tokio            = { workspace = true }
postcard         = { workspace = true }
serde            = { workspace = true }
tempfile         = "3"

[dev-dependencies]
tempfile = "3"
